import type { Metadata } from "next"; 
import { Inter } from "next/font/google"; 
import "./globals.css";
import NavBar from "./components/nav-bar/nav-bar";

const inter = Inter({ subsets: ["latin"] }); 

export const metadata: Metadata = { 
title: "Create Next App", 
description: "Generated by create next app", 
}; 

export default function RootLayout({ 
children, 
}: Readonly<{ 
children: React.ReactNode; 
}>) { 
return ( 
    <html lang="en" data-theme="dim"> 
    <body className={inter.className}>
        <input type="checkbox" value="cupcake" className="toggle theme-controller"/>
        <NavBar />
        <main className="p-5">
            {children}
        </main>
    </body> 
    </html> 
); 
}
